

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nz-depoimento

  backend:
    build: .
    container_name: nz-depoimento-backend
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:example@mongo:27017/nz-depoimento?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]

volumes:
  mongo-data:
